### ISSUE TITLE
Extra Space?

### ISSUE THREAD

**Issue by drew0036** [drew0036/responsive-image-section#1]
Hello @muxlowc, 

This is Holly from YR-1 SEC-040. I am having trouble with extra space around my content on my 608+ webpages, can you please take a look at my code?

Thank you for your help!

**Comment by muxlowc** [comment]
Hey @drew0036 ,

under 38em media query: 
remove “white-space: nowrap;” from wrapper
remove “display: flex;” from .text and .wrapper

That should do it!

**Comment by drew0036** [comment]
Thank you! :)

**Comment by muxlowc** [comment]
@drew0036 can you please close this issue if you got it sorted out?

Thanks!
